### ISSUE TITLE
Empty Studies list

### ISSUE THREAD

**Issue by amhoov** [seermedical/seer-py#107]
Hello, 

I've been able to get the code from this example: https://github.com/seermedical/seer-py/blob/master/Examples/Example.ipynb to run up through the point where client.get_studies is called. However, when I print "studies," I just get an empty list. 

I am using the email/password approach to authenticating. I never specify a server URL to SeerConnect - is that something I need to do to make sure I'm getting the right data? 

**Here's my code:**

import numpy as np
import pandas as pd
from pandas.io.json import json_normalize
import seerpy
from seerpy.utils import plot_eeg

client = seerpy.SeerConnect()
studies = client.get_studies()
print(studies)
for study in studies:
    print(study)

**Here's the output from a terminal:**

(seer) Donnie:Research aaron$ python exploreSeer.py 
Login Successful
[]

Thanks, 
Aaron 

PS - If there's a better way to address this, you can email me at the email address in my github profile.

**Comment by bjdoyle** [comment]
Hi Aaron, by default there is no access to any data on the Seer Cloud, you need to be added to an organisation within the Seer Cloud in order to gain access to that organisation's data. The only publicly accessible data is through the https://www.epilepsyecosystem.org/ organisation. You can register for access through that website. If you have already done so, it may be that you have not yet been granted access (access is not automatic, all applications are vetted before access is granted). Thanks for bringing the issue to our attention, we will update the README to make this clear.

**Comment by amhoov** [comment]
Ok. I have already submitted the Data Request and DUA (as an individual) and gotten assigned a username and password. It allows me to login successfully via the SEER*Stat software as well. I can see data in the different databases through that interface, it's just that that interface is a little clunky (especially via Wine on a Mac!).  I'm primarily interested in brain cancer case data, so I'm not sure if the epilepsy org would be right for me, anyway. Thanks for your help - hopefully we can figure this out, so I can get cranking in Python!

Thanks,
Aaron

**Comment by bjdoyle** [comment]
Ah okay, I see the confusion now. This repo is not associated with https://seer.cancer.gov. It is for access to data on the Seer Cloud, from https://www.seermedical.com.
